### PR TITLE
chore: add group_imports = 'StdExternalCrate' to rustfmt

### PR DESCRIPTION
**Pull request by luke-biel**
This is a proposal, not to be merged before other functionalities are dangling (reapplying rustfmt is easier than rebasing branches). We already do that in half of our files.

### CODE REVIEW

**Comment by Kononnable** [comment]
https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=group_imports

Fine with me. One thing to note here - CDL crates will be grouped together with external dependencies.

>To enable unstable options, set `unstable_features = true` in `rustfmt.toml` or pass `--unstable-features` to rustfmt.

This option is unstable, so I think we should enable unstable features in `rustfmt.toml` instead of passing the command line parameter each time.

**Comment by luke-biel** [comment]
From running this feature, it appears as if I don't have to pass unstable_features flag. Do we set it anywhere in CI?

**Comment by Kononnable** [comment]
If it can run without passing the command line parameter I'm good with it. Maybe rustfmt docs are not up to date or unstable options are enabled on nightly builds by default or something similar.
I don't recall setting it anywhere.

**Comment by luke-biel** [comment]
Close for now. Will reapply change later.

**Pull request closed without merging**
