### PR TITLE
chore(workflow): automatically update branches

### LINKED ISSUE #311: chore: autoupdate branches
Automatically update pull requests

### PR DESCRIPTION
**Pull request by esavier**
fixes #311

### CODE REVIEW

**Comment by frondeus** [comment]
> Branch updates events caused by this action will not trigger any subsequent workflows
from docs.

That's a bit sad because if workflow merges automatically branch with no conflicts we won't know if changes present in develop wouldn't break this branch.

**Comment by Kononnable** [comment]
What is the reasoning behind it? As @frondeus said it looks like it cheats CI(so no 100% safe). If another solution runs those actions its no good either - merging a PR will call CI on all other open PRs.
I just wonder why do we need that.

**Comment by esavier** [comment]
> What is the reasoning behind it? As @frondeus said it looks like it cheats CI(so no 100% safe). If another solution runs those actions its no good either - merging a PR will call CI on all other open PRs.
> I just wonder why do we need that.

I would like for various reasons to have branches updated automatically not manually (i.e. always mergable or if not mergable create a conflict)

It doesn't cheat CI, problem is that workflows can trigger workflows, its a GH limitation, ther are possible workarounds though, i am working on checking those. It would be a separate trigger to restart all open PR's workflows by issuing an empty commit

**Comment by Kononnable** [comment]
>If another solution runs those actions its no good either - merging a PR will call CI on all other open PRs.

I don't think we really want to start a few CI tasks for each merge to develop. Currently(9 open PRs) that would be like 30 long running(5+ minutes)  CI tasks and we can use only one PR either way(once it gets merged other tasks will be restarted anyway).

**Comment by esavier** [comment]
postponed for now

**Pull request closed without merging**
