### PR TITLE
feat: Remove Versioning From Schema Definitions

### PR DESCRIPTION
**Pull request by smores56**
This PR removes versions from schema definitions, as they are not needed and make for unnecessary complication.

### CODE REVIEW

**Review by esavier — DISMISSED** [review]

**Comment by esavier** [comment]
i am cool with it, @luke-biel  second opinion?

**Comment by Kononnable** [comment]
Tests aren't that cool - failing. 

Do we consider this a breaking change?

**Comment by esavier** [comment]
versioning the schemas was not properly designed, i would consider it a bugfix not a breaking change. 
tests have to be updated obviously

**Review by esavier — DISMISSED** [review]
huh, so he went and fixed C# code, total mad lad

**Review by frondeus — APPROVED** [review]

**Review by frondeus — CHANGES_REQUESTED** [review]
CI failing

**Review by frondeus — APPROVED** [review]

**Pull request merged**
